const TestCategories = Object.freeze({
  PERSONAL: "PERSONAL_INFO",
  MBTI: "MBTI",
  FAMILY_ADAPTABILITY_TEST: "FAMILY_ADAPTABILITY_TEST",
  LIFE_PRESSURE_ANALYSIS: "LIFE_PRESSURE_ANALYSIS",
  HAPPY_MARRIAGE_ASSESSMENT: "HAPPY_MARRIAGE_ASSESSMENT"
})

export default TestCategories;